apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
           - mountPath: "/static"
             name: share-volume
      volumes:
        - name: share-volume
          persistentVolumeClaim:
            claimName: share-volume
