apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
          - image: postgres:13-alpine
            imagePullPolicy: IfNotPresent
            name: db
            volumeMounts:
              - name: db-disk
                mountPath: /data
            env:
              - name: POSTGRES_PASSWORD
                value: testpassword
              - name: PGDATA
                value: /data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi              
