---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-dbpvc
spec:
  storageClassName: "nfs"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
