---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.33.10
      ansible_user: vagrant
      ansible_ssh_pass: vagrant
vector:
  hosts:
    vector-01:
      ansible_host: 192.168.33.12
      ansible_user: vagrant
      ansible_ssh_pass: vagrant
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 192.168.33.13
      ansible_user: vagrant
      ansible_ssh_pass: vagrant
